### ISSUE TITLE
User auth

### ISSUE THREAD

**Issue by okj203** [pauulkim/paultrails#5]
slack me when user auth is ready for review

**Comment by okj203** [comment]
- [x] error messages that appear after attempting to sign-up with invalid input need to disappear when the log-in button is clicked and vice-versa

**Comment by okj203** [comment]
- [ ] error messages that appear after attempting to sign-up with invalid input need to disappear when the log-in button is clicked

**Comment by paulwkim** [comment]
Fixed!
